anguage: java

jdk: openjdk11

before_install:
  - chmod +x gradlew
  - wget https://services.gradle.org/distributions/gradle-6.0-bin.zip
  - unzip -qq gradle-6.0-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.0
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stage:
  - dev
  - prod

install: skip

addons:
  sonarcloud:
    organization: "oscarromero1717"

jobs:
  include:
    - stage: dev
      name: "build & unit test & sonar qube"
      script:
        - ./gradlew build
        - ./gradlew build test
        - ./gradlew sonarqube

    - script: echo "I want to deploy to heroku"
      name: "deploy"

